name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - main
      - add-rust-client # Test CI
    paths:
      - '**.rs'
      - '**.toml'

jobs:

  check-clippy:
    runs-on: ubuntu-latest
    steps:

    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@a40b8845c0683271d9f53dfcb887a7e181d3918b # 0.9.1
      with:
        access_token: ${{ github.token }}

    - uses: actions/checkout@v3

    - uses: actions-rs/toolchain@16499b5e05bf2e26879000db0c1d13f7e13fa3af # v1.0.7
      with:
        profile: minimal
        toolchain: stable
        override: true
        components: clippy

    - uses: Swatinem/rust-cache@842ef286fff290e445b90b4002cc9807c3669641 # v1.3.0

    - name: Run cargo clippy
      uses: actions-rs/cargo@844f36862e911db73fe0815f00a4a2602c279505 # v1.0.3
      with:
        command: clippy 
        args: -- -D warnings