name: Create Release
on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    name: Building Release
    runs-on: ubuntu-latest
    steps:
      - name: Checking out repository...
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # required for the changelog to work correctly
          ref: ${{ github.event.inputs.gitRef }}

      - name: Setting up Go 1.18
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Running GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
